INSERT INTO Genre (Name, Description, Genre_ID) VALUES('Accounting', 'As future indeed ahead him.', 0),
('Anthropology', 'Film sign best suffer pay rest that budget.', 1),
('Art', 'Recognize return hour quality fast everyone.', 2),
('Autobiography', 'Everybody image interesting opportunity year.', 3),
('Biography', 'Him attack democratic prove hair.', 4),
('Biology', 'Adult heart our floor religious.', 5),
('Business', 'Friend will note time.', 6),
('Chemistry', 'Discover shoulder early enough difficult than.', 7),
('Children', 'Less you number hit father.', 8),
('Comics', 'Cell throughout much party picture could.', 9),
('Computer Science', 'Network into point leader option mind produce pass.', 10),
('Consulting', 'Company majority play want trip.', 11),
('Cooking', 'Course share professor indeed.', 12),
('Criminal Justice', 'Management often front everything.', 13),
('Customer Service', 'Try lot authority rule keep stock your main.', 14),
('Dance', 'Way serve character.', 15),
('Dentistry', 'Happy administration trial section fly investment foreign.', 16),
('Drama', 'Such happy true must quickly.', 17),
('Economics', 'Night poor good knowledge.', 18),
('Education', 'Shake read white particularly key center leg.', 19),
('Engineering', 'Response stuff dark all east five audience.', 20),
('Entrepreneurship', 'Consider represent century it.', 21),
('Fantasy', 'Take country risk produce off simple address according.', 22),
('Fiction', 'Car person the read poor.', 23),
('Film', 'Capital get quickly across ground involve.', 24),
('Finance', 'Throw party human discuss.', 25),
('Fitness', 'Challenge place benefit forward possible for close.', 26),
('Geography', 'Throughout blood bring west type dinner report.', 27),
('Graphic Novel', 'Run step thousand spring since.', 28),
('Health', 'Her peace agreement imagine guy medical rest.', 29),
('History', 'Affect necessary drop fast direction.', 30),
('Horror', 'Against almost first democratic particularly hot.', 31),
('Human Resources', 'Third score lose explain board memory.', 32),
('Information Technology', 'Floor ago week road.', 33),
('Innovation', 'Walk beautiful factor well trip.', 34),
('Journalism', 'Own consider nor purpose film avoid.', 35),
('Law', 'Past threat wonder guess every spend animal.', 36),
('Leadership', 'Exist term newspaper art.', 37),
('Literature', 'Side him age fish others beyond.', 38),
('Logistics', 'Total medical scientist us guy gas.', 39),
('Management', 'Quite director inside yet.', 40),
('Marketing', 'Industry energy increase nor.', 41),
('Mathematics', 'Increase born blue see conference.', 42),
('Medicine', 'Report police effect yourself provide certain until.', 43),
('Music', 'System conference two hope.', 44),
('Mystery', 'Left particular behavior section forget week true away.', 45),
('Non-Fiction', 'Imagine risk real he wonder worry letter.', 46),
('Nursing', 'Rather watch bar sit he fact.', 47),
('Operations', 'Term day why perform set father garden.', 48),
('Pharmacy', 'Property kid involve Democrat.', 49),
('Philosophy', 'System movement government time.', 50),
('Physics', 'Security blood middle seek.', 51),
('Poetry', 'Rest right writer leg reason floor.', 52),
('Political Science', 'Consider information first eye.', 53),
('Politics', 'Debate concern join movie night bed.', 54),
('Psychiatry', 'Own physical onto impact office price.', 55),
('Psychology', 'Model result study begin imagine maybe collection.', 56),
('Radio', 'Public kid lead law.', 57),
('Religion', 'Low bed choice individual week surface keep Democrat.', 58),
('Romance', 'Election dark successful son pick along.', 59),
('Sales', 'Image quite full nearly purpose.', 60),
('Science', 'Especially economic matter choice month particularly.', 61),
('Science Fiction', 'Democrat by modern study.', 62),
('Self-Help', 'Home those short.', 63),
('Sociology', 'Dog smile assume smile add.', 64),
('Spirituality', 'Sure light step run former next power range.', 65),
('Sports', 'Specific until program.', 66),
('Strategy', 'Right want glass see.', 67),
('Supply Chain', 'So play either prove trial.', 68),
('Technology', 'Play recognize team can so similar body prove.', 69),
('Television', 'Smile natural political up.', 70),
('Theatre', 'Culture keep arm subject stay.', 71),
('Theology', 'Foreign bed thousand eat civil exactly beyond.', 72),
('Thriller', 'Fact religious box.', 73),
('Travel', 'Section strategy describe including.', 74),
('Veterinary', 'Police only responsibility to world provide project.', 75),
('Young Adult', 'Audience the themselves employee.', 76);

