INSERT INTO Country (Name, Country_ID) VALUES('USA', 0),
('Canada', 1),
('Mexico', 2),
('Brazil', 3),
('Argentina', 4),
('Chile', 5),
('UK', 6),
('Germany', 7),
('France', 8),
('Italy', 9),
('Spain', 10),
('Russia', 11),
('China', 12),
('Japan', 13),
('India', 14),
('Australia', 15),
('South Africa', 16),
('Nigeria', 17),
('Egypt', 18),
('Saudi Arabia', 19),
('Iran', 20),
('South Korea', 21),
('North Korea', 22),
('Uzbekistan', 23);

